title: Isami Takeuchi's Portfolio of Cybersecurity Projects
description: Welcome to my porfolio! I recently graduated with my Bachelor's Degree in Computer Science with a Concentration in Cybersecurity and am looking to showcase my skills through experience with personal projects. I have a passion for helping people and am looking to start my career as a SOC Analyst so I will be documenting my progress over time here. Cyber Security is amazing and all but don't tell anyone but I am a pro soccer player at heart <3.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
